# Dependencies
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Will Millar
tagline:          Product Designer
description:      Empathetic design for better experiences
url:              http://willmillar.com

author:
  name:           Will Millar

paginate:         1

# Custom vars
version:          6.0.0

github:
  repo:           https://github.com/willmillar/willmillar.github.io

excerpt_separator: <!--more-->

navigation:
      - text: Will Millar
        url: /
      - text: Work
        url: /work/
        layout: project