# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Will Millar
tagline:          Designer
description:      Empathetic design for better experiences
url:              http://willmillar.com

author:
  name:           Will Millar
  url:            https://twitter.com/ideastate

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/willmillar/willmillar.github.io

navigation:
      - text: Will Millar
        title: Home - Will Millar Experience Designer
        url: /
      - text: Projects
        title: An introduction to the project
        url: /projects/
      - text: Blog
        title: Bloggerino
        url: /blog/ 