# Setup
title:            Will Millar
tagline:          Product Designer
description:      Empathetic design for better experiences
url:              http://willmillar.com

author:
name:             Will Millar

exclude:
                - __old-site

# Permalinks
permalink:        pretty

# Custom vars

version:          6.0.0

github:
  repo:           https://github.com/willmillar/willmillar.github.io

excerpt_separator: <!--more-->