# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Will Millar
tagline:          Designer
description:      Empathetic design for better experiences
url:              http://willmillar.com

author:
  name:           Will Millar
  url:            https://twitter.com/ideastate

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/willmillar/willmillar.github.io

excerpt_separator: <!--more-->

navigation:
      - text: Will Millar
        url: /
      - text: Projects
        url: /projects/
        layout: project
      - text: Blog
        url: /blog/
        layout: post